version: '3.3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0
    depends_on:
      - selenium

  pytest:
    build: .
    command: pytest tests/ --html=reports/unit_test_report.html
    volumes:
      - .:/app
    depends_on:
      - web

  selenium:
    image: selenium/standalone-chrome:123.0
    shm_size: 2g
    ports:
      - "4444:4444"
