version: '3.3'

services:
  app:
    build: .
    ports:
      - "5001:5000"
    environment:
      - PYTHONUNBUFFERED=1

  selenium:
    image: seleniarm/standalone-chromium
    platform: linux/arm64
    ports:
      - "4444:4444"
    shm_size: 2g
