services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/todo_db
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
#
#  test:
#    build: .
#    volumes:
#      - .:/app
#    environment:
#      - FLASK_APP=app.py
#      - FLASK_ENV=testing
#      - DATABASE_URL=postgresql://postgres:postgres@db:5432/todo_test_db
#    depends_on:
#      - db
#    command: pytest

volumes:
  postgres_data: