version: '3.3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    shm_size: 2g